
name: 'Set NX Shas'
description: 'Sets the base and head shas for nx based on git tags'
inputs:
  base:  # id of input
    description: 'The tag to consider as the base sha for nx'
    required: false
outputs:
  base_sha: # id of output
    description: 'The base sha to use as the base for nx affected command'
  head_sha:
    description: 'the head sha to use as the head for nx affected command'
runs:
  using: 'node16'
  main: 'dist/index.js'
