on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    name: Run integrations tests
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
      - run: npm i @vercel/ncc
      - run: npm ci
      - run: npm run build --if-present
      - name: Run GH action
        id: set_nx_shas
        uses: ./
      - name: Get the output vars
        run: |
          echo "The base sha is ${{ steps.set_nx_shas.outputs.base_sha }}"
          echo "The head sha is ${{ steps.set_nx_shas.outputs.head_sha }}"
