on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Run the action
        id: set_nx_shas
        uses: equipapp/set-nx-shas@v0.0.1
      - name: Get the output vars
        run: |
          echo "The base sha is ${{ steps.set_nx_shas.outputs.base_sha }}"
          echo "The head sha is ${{ steps.set_nx_shas.outputs.head_sha }}"
