##
# Run unit test and the action itself
##
name: Unit Test

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i @vercel/ncc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  # # test action works running from the graph
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - run: npm ci
  #   - uses: ./
  #     with:
  #       milliseconds: 1000
