##
# Run unit tests
##
name: Unit Test

on:
  pull_request:
  push:
    branches:
      - main
      - feature/**
      - hotfix/**
      - bugfix/**

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i @vercel/ncc
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run ci:test
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Mocha Tests
          path: tmp/reports/report.json
          reporter: mocha-json
